### ISSUE TITLE
摩拜单车的爬虫还能用吗？

### ISSUE THREAD

**Issue by tzhao0311** [derekhe/mobike-crawler#1]
您好！请问您写的摩拜单车的爬虫还能用吗？我看您在备注里说不能用了

**Comment by zhangqiongyu** [comment]
我跑了下，可以爬，但是数据正确性正在验证中......估计十九不准确了......

**Comment by tzhao0311** [comment]
现在是要登录了才能爬出正确的数据了吧，不知道添加一个登录模块能不能爬到，会不会被封。

**Comment by zhangqiongyu** [comment]
不知道啊，膜拜没有pc版，想要模拟登录感觉好蛋疼，iPhone证书也不好导出来，您有什么好方法吗？

**Comment by tzhao0311** [comment]
我也不太清楚，没试过，不过应该是可以的吧

**Comment by zhangqiongyu** [comment]
不知道咋模拟登录，感觉很蛋疼啊，要是有网页版的就好说多了。。。不过Android手机应该好抓包一点

**Comment by derekhe** [comment]
未登录获得的都是假数据，基本上是拿到accesstoken就可以，但里面还有一些其他的变量不清楚怎么回事。android是360加固的，如果能够反编译出来看看或许有线索。

另外微信小程序也可以看看，毕竟是js代码。

**Comment by derekhe** [comment]
@zhangqiongyu 模拟登陆啥的我已经搞定，但不方便公开。
@tzhao0311 登陆后爬取的代码已经放在login分支，可以参考。

**Comment by zhangqiongyu** [comment]
请问您是通过fiddler抓取android手机上的包得到的accesstoken吗？以及登陆爬取，会不会被封号？谢谢




发自网易邮箱大师
在2017年05月16日 22:51，hesicong 写道：

@zhangqiongyu 模拟登陆啥的我已经搞定，但不方便公开。
@tzhao0311 登陆后爬取的代码已经放在login分支，可以参考。

**Comment by yyuanxuan** [comment]
尝试了登录爬取，但是摩拜那边似乎限制了请求频率，所以还是不可用的感觉~

**Comment by zhangqiongyu** [comment]
摩拜反爬还是比较猛啊，感觉要爬的话还得多账号去爬




发自网易邮箱大师
在2017年05月17日 21:31，yyuanxuan 写道：

尝试了登录爬取，但是摩拜那边似乎限制了请求频率，所以还是不可用的感觉~
