### ISSUE TITLE
Please translate in English 

### ISSUE THREAD

**Issue by Aarbel** [derekhe/mobike-crawler#11]
:wink:

**Comment by derekhe** [comment]
Currently this method is not able to grab enough data for a whole city at high frequency because mobike only gives 10 bikes at the moment. The whole idea for this repo is ok. There are other methods to the bikes by other APIs, but I can't share it with you guys.

**Comment by PierrickP** [comment]
Only 10 ? i disagree, i crawl more than 10 in one request.
But i'm sorry, i can't help you more, i don't speak chinese yet.

**Comment by derekhe** [comment]
I checked right now they return around 20 bikes.
