### ISSUE TITLE
请问爬取数据里的表头名称是什么意思？

### ISSUE THREAD

**Issue by ywb1016** [derekhe/mobike-crawler#6]
请问那个摩拜单车里面的distance  disid 是什么？

**Comment by ywb1016** [comment]
还有，您的那个数据分析怎么没了？

**Comment by derekhe** [comment]
distance 指的是查询位置和车之间的直线距离
disid 应该是和车的ID一样，没啥太大区别。

**Comment by derekhe** [comment]
数据分析服务器关闭了，成本比较高。
