### ISSUE TITLE
Why use `ujson` ? 

### ISSUE THREAD

**Issue by zxj5470** [derekhe/mobike-crawler#7]
your code ran faster than mine.
But It will cost much time in install something like `ujson`,`Proxy` and so on.
Why use `ujson` instead of `json` which is a `stdlib`???

**Comment by derekhe** [comment]
ujson的处理速度对比原生的json快很多，在大量爬去的时候速度优势很明显。

**Comment by zxj5470** [comment]
突然想到还有一个问题，sqlite这样insert好像会把重复的数据给算进去吧……

**Comment by derekhe** [comment]
重复的是有用的，因为时间不一样
